### ISSUE TITLE
推酷域名

### ISSUE THREAD

**Issue by xuchen-xiaoying** [gurureader/ning#4]
@gurureader @kafka0102 请问下，推酷现在域名怎么样啦？一直在耐心等待中。
有预期的恢复时间吗？因为现在每天都在刷 tuicool.com 域名看是否恢复了。。。，所以希望了解下进度
如果推酷能回来，等几个月都是值得的~ 加油！！！

**Comment by xuchen-xiaoying** [comment]
有同样关心的小伙伴吗？

**Comment by songxing10000** [comment]
有啊，没有推酷感觉人生没有意义了，期待回归

**Comment by xuchen-xiaoying** [comment]
> 有啊，没有推酷感觉人生没有意义了，期待回归

@songxing10000 我的感觉也是类似的。 你能联系上负责人吗? 我通过各种渠道（微信公众号、微博、邮件等），都没有联系上 😭
